# -*- coding: utf-8 -*-
"""Lab0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3MM3F4LtfbtAwg9sj9htpQwTNeWpKB1
"""

import numpy as np
# (fila, columna)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr = np.array([1, 2, 3])
non_squared = np.array([[1, 2], [3, 4], [5, 6]])
trasposed_matrix = np.array([[1, 1, 5], [1, 2, 3], [5, 3, 4]])

def esCuadrada(A):
  return A.shape[0] == A.shape[1]

assert(esCuadrada(matrix) == True)
assert(esCuadrada(non_squared) == False)

## Creo nueva Matriz B con misma dimensión que A. Podemos asumir que A es una matriz de numpy y todas sus filas tienen la misma cantidad de elementos.
def crearMatrizConDimensionesDe(A):
  return np.zeros((A.shape[0], A.shape[1]))

def triangSup(A):
  if not(esCuadrada(A)):
    return "Invalid Square Matrix"
  matrix_b = crearMatrizConDimensionesDe(A)

  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      if j > i:
        matrix_b[i][j] = A[i][j]

  print(A)
  print(matrix_b)

print(triangSup(matrix))

def triangInf(A):
  if not(esCuadrada(A)):
    return "Invalid Square Matrix"
  matrix_b = crearMatrizConDimensionesDe(A)

  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      if j <= i:
        matrix_b[i][j] = A[i][j]

  print(A)
  print(matrix_b)

print(triangInf(matrix))

def diagonal(A):
  if not(esCuadrada(A)):
    return "Invalid Square Matrix"
  matrix_b = crearMatrizConDimensionesDe(A)

  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      if j == i:
        matrix_b[i][j] = A[i][j]

    print(A)
    print(matrix_b)

print(diagonal(matrix))

#Traza: solo matrices cuadradas. Es la suma de la diagonal.
def traza(A):
  if not(esCuadrada(A)):
    return "Invalid Square Matrix"
  sum = 0

  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      if j == i:
        sum+= A[i][j]

  return sum

print(traza(matrix))

#Traspuesta: cambiar filas x columnas y viceversa.
def traspuesta(A):
  matrix_b = crearMatrizConDimensionesDe(A)

  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      matrix_b[j][i] = A[i][j]

  print(A)
  print(matrix_b)
  return matrix_b

print(traspuesta(matrix))

#Matriz Simétrica: A = At (t: traspuesta)
def esSimetrica(A):
  return np.array_equal(A, traspuesta(A))

assert(esSimetrica(matrix) == False)
assert(esSimetrica(trasposed_matrix) == True)

## A = n x m, x = m x 1. Devolver el vector resultado de longitud n x 1.
def calcularAx(A, x):
  matrix_b = np.zeros((A.shape[1]))

  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        matrix_b[i] += A[i][j] * x[j]

  print(A)
  print(x)
  print(matrix_b)
  return matrix_b

## (1*1) + (2*2) + (3*3) = 15
## (4*1) + (5*2) + (6*3) = 32
## (7*1) + (8*2) + (9*3) = 50

assert(np.array_equal(calcularAx(matrix, arr), np.array([14, 32, 50])))

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def intercambiarFilas(A, i, j):
  for k in range(A.shape[0]):
    for l in range(A.shape[1]):
      if i == k:
        old = A[j][l]
        A[j][l] = A[i][l]
        A[i][l] = old

  print(A)

print(matrix)
intercambiarFilas(matrix, 0, 1)

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

##Multiplicar la fila entera de i, por j*s.
def sumar_fila_multiplo(A, i, j, s):
  for k in range(A.shape[0]):
    for l in range(A.shape[1]):
      if i == k:
        value = A[j][l] * s ##ValFilaColumna*s. Ahora lo sumo con el de i j.
        A[i][l] = A[i][l] + value
  print(A)

sumar_fila_multiplo(matrix, 0, 1, 2)

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_dominante = np.array([[100, 0, 0], [0, 150, 0], [0, 0, 200]])

# Si la suma de la diagonal es mayor que la suma de cada fila (con valores absolutos).
def esDiagonalmenteDominante(A):
    sum_traza = traza(A)
    sum_filas = np.zeros(A.shape[0])

    for i in range(A.shape[0]):
      for j in range(A.shape[1]):
        sum_filas[i] += A[i][j]

    return np.all(sum_traza > sum_filas)

assert(esDiagonalmenteDominante(matrix) == False)
assert(esDiagonalmenteDominante(matrix_dominante) == True)

def crearMatrizCuadradaDesdeVector(A):
  return np.zeros((A.shape[0], A.shape[0]))

# Ej.: v = [1, 2, 3] la matriz es [[1, 2, 3], [2, 3, 1], [3, 1, 2]]
def matriz_circulante(v):
  matrix_circulante = crearMatrizCuadradaDesdeVector(v)

  for i in range(matrix_circulante.shape[0]):
    for j in range(matrix_circulante.shape[1]):
      matrix_circulante[i][j] = v[(i+j) % matrix_circulante.shape[0]]

  print(matrix_circulante)

matriz_circulante(np.array([1, 2, 3]))
# v = [1, 2, 3]
# m = [[0, 1, 2], [1, 2, 0], [2, 0, 1]]