# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__saCE6Q5Vy-cJ4dENJCRNO-vAdk1dlg
"""

# Ejercicio 1: el problema es que los números flotantes no se pueden representar al 100% en la computadora. El 0.1 no es 0.100...000 como nos gustaría sino 0.100...555
format(0.1, '.20f')
print(format(0.1, '.20f'))

x = 0.1 + 0.1 + 0.1
y = 0.3

print(format(x, '.20f'))
print(format(y, '.20f'))
print(x == y)

## La respuesta del print(x==y) es correcta. El x == y compara el número entero almacenado. Lo que nos miente son el print de los flotantes.

# Ejercicio 2
# El problema es que, al usar números de punto flotante (`float`), la representación
# decimal que vemos puede ocultar pequeñas diferencias respecto del valor almacenado.
# Esto ocurre porque `float` utiliza IEEE-754 en base 2, y algunos números decimales,
# como 0.1, no pueden representarse exactamente en binario.

# Por ejemplo, 0.1 se almacena como una aproximación. Por eso:
# 1.0 - 0.1 ≈ 0.90000000000000002220
# y no exactamente 0.90000000000000000000.

# Además, al realizar varias operaciones, esos pequeños errores de redondeo pueden
# acumularse. En este caso, cada resta de 0.1 puede introducir una pequeña diferencia
# respecto del valor decimal que esperamos.

a = 1.0
while a != 0.1:
  print(format(a, '.20f'))
  a = a - 0.1

print("fin")

from decimal import Decimal

# Solución 1: usar Decimal
a = Decimal("1.0")
while a != Decimal("0.1"):
  print(format(a, '.20f'))
  a = a - Decimal("0.1")
  if(a < 0):
      break;

print("fin")

from decimal import Decimal

# Solución 2: asumir un poco de error. sin acotar
a = 1.0
while a >= 0.1:
  print(format(a, '.20f'))
  a = a - 0.1
  if(a < 0):
      break;

print("fin")

from decimal import Decimal

# Solución 3: tolerar un % de error, con una cota como techo. Los nros que estén dentro de la tolerancia, los considero semánticamente iguales.
a = 1.0
tol=1e-5
while abs(a-0.1) > tol:
  print(format(a, '.20f'))
  a = a - 0.1
  if(a < 0):
      break;

print("fin")

1/4 + 1/32 + 1/64 + 1/256

# Ejercicio 3: una inocente suma
# 1. Comparen el resultado de hacer 0.3 + 0.25 con el de hacer 0.3 − 0.25. ¿En ambos casos obtienen el resultado esperado? ¿Por qué?
# 2. Escriban el número 0.25 en base 2. ¿Cómo queda expresado en términos de su mantisa y exponente?
# 3. Escriban el número 0.3 en base 2. ¿Qué dificultades aparecen al escribir 0.3 en binario? ¿Se puede escribir exactamente con una mantisa finita?
a = 0.3 + 0.25
b = 0.3 - 0.25

print(format(a, '.20f'))
print(format(b, '.20f'))


"""
1. En ambas operaciones se utilizan exactamente las mismas representaciones binarias de 0.3 y 0.25.
Sin embargo, cada operación produce un resultado que debe volver a redondearse al número representable más cercano.
En la suma, el error no resulta visible al imprimir el float como 0.55; en la resta, el error sí queda expuesto como 0.049999....

2. Como es un número con decimales que empieza con 0,
tenemos que sacar los decimales hasta que arranque con un numero y el decimal sea 0.

Multiplicamos sucesivamente por 2 y nos quedamos con la parte entera.
0.25 x 2 = 0.5

El resultado tiene parte entera 0. Este es el primer bit después de la coma.
Hasta ahora formamos: 0.0 base 2

0.5 x 2 = 1.0
El resultado tiene parte entera 1. Este es el segundo bit después de la coma.

Hasta ahora formamos: 0.01 base 2.
Como la parte fraccionaria del resultado anterior es "0" terminamos.

Por ende, nos queda
0.25 base 10 = 0.01 base 2.

Verificamos: 0 x 2^-1 + 1 x 2^-2 (notar que hablamos del . en adelante del 0.01)
Esto nos da 0.25 base 10.

¿Y para conseguir la mantisa + exponente?
Movemos a la izquierda hasta tener un 1.

0.01 -> 1.0.
Como lo movimos 2 lugares hacia la derecha, entonces
0.01 base 2 = 1.0 base 2 * 2^-2.

Por lo tanto:
Mantisa: 1.0 base 2.
Exponente: -2

3. Mismo algoritmo.
0.30 base 10

0.30 * 2 = 0.6 (nos quedamos con el 0)
hasta ahora tenemos 0.0 en base 2.

0.6 * 2 = 1.2 (nos quedamos con el 1).
hasta ahora tenemos 0.01 en base 2.

0.2 * 2 = 0.4 (nos quedamos con el 0).
hasta ahora tenemos 0.010 en base 2.

0.4 * 2 = 0.8 (nos quedamos con el 0)
hasta ahora tenemos 0.0100

0.8 * 2 = 1.6 (nos quedamos con el 1)
hastas ahora tenemos 0.01001

0.6 * 2 = 1.2 (nos quedamos con el 1)
hasta ahora tenemos 0.010011

0.2 * 2 = 0.4 (nos quedamos con el 0)
hasta ahora tenemos 0.0100110

0.4 * 2 = 0.8 (nos quedamos con el 0)
hasta ahora tenemos 0.01001100

0.8 = 2 = 1.6 ... aca se empieza a repetir el 0011
0.010011001100....

Entonces, no podemos escribirlo con una mantisa finita.

Con el 0.25 en base 10 podemos guardar el valor binario exacto con una cantidad finita de bits.

Pero el 0.3 necesitaria infinitos bits. Una computadora tiene una mantisa finita, asi que en algun momento tiene que cortar/redondear.
Eso quiere decir que no guardaríamos exactamente 0.3, sino que algo muy cercano.

"""

"""
Ejercicio 4 (números no tan distintos):
a) ¿Cuánto da sqrt(2) ** 2 - 2?

Matemáticamente da 0, ya que (sqrt(2))^2 = 2.

Sin embargo, sqrt(2) es irracional y no puede representarse exactamente
con una cantidad finita de bits. Por eso, la computadora almacena una
aproximación de sqrt(2).

Luego, al elevar esa aproximación al cuadrado, el resultado vuelve a estar
sujeto a redondeo. Finalmente, al restarle 2, puede quedar un valor muy
cercano a 0, pero no necesariamente exactamente 0.

Por lo tanto, aparecen errores de representación/redondeo en distintas
etapas: al representar sqrt(2), al realizar el cuadrado y al efectuar
la resta.
"""

import numpy as np
val = np.sqrt(2)**2 -2
print(val)
print(format(val, '.20f'))

"""
Ejercicio 4.b

b) Graficar a y b, para ver cual es la mejor resiste la pérdida de valores significativos.
Seguro sea la que NO tiene división.

Parece que no che. La que tiene división es MEJOR.

Lo importante de este ejercicio es notar que dos expresiones equivalentes matemáticamente NO
garantizan que funcionen igual en una computadora.

El problema de la expresión A es que si x es DIMINUTO, tenés un número MUY cercano al 1 y otro muy cercano al 1.
¿Qué pasa? la resta catastrófica.

Aprendizaje: restar dos números muy cercanos - peligro.

Ej.: sqrt(1+2x**2) es aprox 1.000000000000000001 on x = 10**-16
Entonces, 1.00000000000001 - 1 = 0.000000000000000000001

La segunda expresión no tiene este problema porque estás sumando valores siempre del mismo signo y magnitud.
"""


import matplotlib.pyplot as plt
x = np.linspace(0, 5e-8, 100)

# Expresión A
y_a = np.sqrt(2*x**2 + 1) - 1

# Expresión B
y_b = (2*x**2) / (np.sqrt(2*x**2 + 1) + 1)

# Graficamos ambas
plt.plot(x, y_a, label="Expresión A")
plt.plot(x, y_b, label="Expresión B")

plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid()

plt.show()

1 - 0.9999999999999999

"""
Ejercicio 5 (acumulación del error)

Calcular: x1 = sqrt(2), x_n+1 = (x_n * x_n)/sqrt(2) para i = 1, ..., 100 y graficar.

¿Cuál es el problema de acá?

Cada vez que calculamos sqrt(2), tenemos un pequeño error de representación. Eso ya lo sabemos.
El problema es que, al requerir el resultado anterior para calcular el siguiente, el error de ese resultado también se propaga a la siguiente iteración. Es decir, cada nuevo cálculo parte de un valor que ya contiene error y, además, puede introducir nuevos errores de redondeo.
En este caso particular, la recurrencia no solo propaga el error, sino que lo amplifica en cada iteración. Para errores pequeños, aproximadamente se duplica en cada paso.
Por lo tanto, el cálculo se aleja cada vez más del valor esperado. Eventualmente, el error crece de forma muy rápida hasta que el número supera el máximo representable por float64, produciendo un overflow y dando como resultado inf.
Mentalmente, yo lo veo así: error nuevo = error propagado de antes + error local de esta operación.

"""
import matplotlib.pyplot as plt

arr = [np.sqrt(2)]

for i in range(1, 100):
    arr.append((arr[i-1] * arr[i-1]) / np.sqrt(2))

print(arr)

plt.plot(arr)

import numpy as np

# Recibe dos números x e y. Calcula el error de aproximar x usando y en float64.
#
# Ojo: la idea original de este ejercicio quedó vieja.
# Antes, Python podía trabajar solo con floats de 32 bits, y el truco consistía
# en convertir el número a float64 para calcular el error con mayor precisión.
#
# Actualmente, el float de Python es de 64 bits. Por eso, para simular la
# aproximación, primero forzamos x a float32 (perdemos precisión) y luego
# calculamos el error comparándolo con y, que se mantiene en float64.
#
# En otras palabras: primero "cortamos" x a 32 bits y después calculamos
# cuánto se diferencia de y en 64 bits.

def error(x, y):
    x = np.float32(x)  # Forzamos x a 32 bits
    return abs(x - y)

def error_relativo(x, y):
  x = np.float32(x)

  return abs(x-y) / abs(x)

print(error_relativo(0.3, 0.25))

#Acá los docentes deberian definir un buen umbral de error.
def matricesIguales(A, B):
    if A.shape != B.shape:
        return False

    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if error(A[i, j], B[i, j]) > np.float64(0.7e-1):
                return False

    return True

assert matricesIguales(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4]])) == True

assert matricesIguales(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 5]])) == False

assert matricesIguales(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4.05]])) == True

assert matricesIguales(np.array([[1, 2], [3, 4]]), np.array([[1, 2], [3, 4.1]])) == False

assert matricesIguales(np.array([[1, 2]]), np.array([[1], [2]])) == False

assert matricesIguales(np.array([[1, 2, 3]]), np.array([[1, 2]])) == False

assert matricesIguales(np.array([[1], [2], [3]]), np.array([[1], [2]])) == False

assert matricesIguales(np.array([[1.05, 2.05], [3.05, 4.05]]),
                       np.array([[1, 2], [3, 4]])) == True

assert matricesIguales(np.array([[1.05, 2.05], [3.05, 4.2]]),
                       np.array([[1, 2], [3, 4]])) == False

